package vistas.FrmAdministrador;

import controladores.ReportesFinancierosController;
import controladores.ReportesFinancierosController.BalanceGeneralResult;
import controladores.ReportesFinancierosController.EstadoResultadosResult;
import controladores.ReportesFinancierosController.LineaReporte;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelos.Usuario;
import vistas.FrmMenuPrincipal;

/**
 * Módulo de Estados Financieros Automáticos.
 * Genera reportes dinámicos clasificados por el primer dígito del código contable:
 * 1 (Activo) = 2 (Pasivo) + 3 (Capital contable)
 * 5 (Ingresos) - 4 (Costos y Gastos) = Utilidad
 */
public class FrmEstadosFinancieros extends javax.swing.JPanel {

    private final Usuario usuario;
    private final FrmMenuPrincipal menuPrincipal;
    private final ReportesFinancierosController controller;

    // Componentes Balance General
    private DefaultTableModel modeloActivos;
    private DefaultTableModel modeloPasivos;
    private DefaultTableModel modeloPatrimonio;
    private JLabel lblTotalActivoForm;
    private JLabel lblTotalPasivoMasPatrimonioForm;
    private JLabel lblBannerBalanceForm;

    // Componentes Estado de Resultados
    private DefaultTableModel modeloResultados;
    private JLabel lblVentasNetasForm;
    private JLabel lblCostoVentasForm;
    private JLabel lblUtilidadBrutaForm;
    private JLabel lblGastosOperacionForm;
    private JLabel lblUtilidadEjercicioForm;
    private JLabel lblUtilidadNetaForm;

    public FrmEstadosFinancieros(Usuario usuario, FrmMenuPrincipal menuPrincipal) {
        this.usuario = usuario;
        this.menuPrincipal = menuPrincipal;
        this.controller = new ReportesFinancierosController();

        initComponents();
        postInit();
    }

    /**
     * Conecta listeners y carga datos iniciales tras el initComponents().
     */
    private void postInit() {
        btnRefrescarERForm.addActionListener(e -> generarReportes());
        generarReportes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);

        // =========================================================
        // 1. ENCABEZADO
        // =========================================================
        pnlHeaderEF = new JPanel(new BorderLayout());
        pnlHeaderEF.setBackground(new Color(30, 41, 59));
        pnlHeaderEF.setBorder(BorderFactory.createEmptyBorder(15, 25, 15, 25));

        JPanel pnlTitulosEF = new JPanel();
        pnlTitulosEF.setLayout(new javax.swing.BoxLayout(pnlTitulosEF, javax.swing.BoxLayout.Y_AXIS));
        pnlTitulosEF.setOpaque(false);

        lblTituloEF = new JLabel("ESTADOS FINANCIEROS — LA VAQUITA, S.A. DE C.V.");
        lblTituloEF.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblTituloEF.setForeground(Color.WHITE);

        lblSubtituloEF = new JLabel("IVA incluido · Inventario final a precio unitario de compra · Sin ISR");
        lblSubtituloEF.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblSubtituloEF.setForeground(new Color(203, 213, 225));

        pnlTitulosEF.add(lblTituloEF);
        pnlTitulosEF.add(javax.swing.Box.createVerticalStrut(4));
        pnlTitulosEF.add(lblSubtituloEF);
        pnlHeaderEF.add(pnlTitulosEF, BorderLayout.WEST);

        // =========================================================
        // 2. PESTAÑAS
        // =========================================================
        tabbedPaneEF = new JTabbedPane();
        tabbedPaneEF.setFont(new Font("Segoe UI", Font.BOLD, 13));

        // =====================================================================
        // TAB 1: BALANCE GENERAL (1 = 2 + 3)
        // =====================================================================
        JPanel pnlTabBalance = new JPanel(new BorderLayout(0, 10));
        pnlTabBalance.setBackground(new Color(241, 245, 249));
        pnlTabBalance.setBorder(BorderFactory.createEmptyBorder(12, 15, 12, 15));

        JPanel pnlGridBalance = new JPanel(new GridLayout(1, 2, 15, 0));
        pnlGridBalance.setOpaque(false);

        // Columna Izquierda: ACTIVOS (1)
        JPanel pnlColActivosForm = new JPanel(new BorderLayout(0, 5));
        pnlColActivosForm.setBackground(Color.WHITE);
        pnlColActivosForm.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(34, 197, 94), 2),
                "CÓDIGO 1: ACTIVO (Bienes y Derechos)", 0, 0, new Font("Segoe UI", Font.BOLD, 13), new Color(22, 101, 52)),
            BorderFactory.createEmptyBorder(6, 8, 8, 8)
        ));

        modeloActivos = new DefaultTableModel(new Object[][]{}, new String[]{"Código", "Cuenta", "Categoría", "Saldo ($)"}) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblActivosForm = new JTable(modeloActivos);
        tblActivosForm.setRowHeight(24);
        tblActivosForm.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        tblActivosForm.getTableHeader().setBackground(new Color(30, 41, 59));
        tblActivosForm.getTableHeader().setForeground(Color.WHITE);

        lblTotalActivoForm = new JLabel("TOTAL ACTIVO: $0.00", SwingConstants.RIGHT);
        lblTotalActivoForm.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblTotalActivoForm.setForeground(new Color(22, 101, 52));
        lblTotalActivoForm.setBorder(BorderFactory.createEmptyBorder(6, 6, 6, 6));

        pnlColActivosForm.add(new JScrollPane(tblActivosForm), BorderLayout.CENTER);
        pnlColActivosForm.add(lblTotalActivoForm, BorderLayout.SOUTH);

        // Columna Derecha: PASIVOS (2) Y PATRIMONIO (3)
        JPanel pnlColPasivoPat = new JPanel(new GridLayout(2, 1, 0, 10));
        pnlColPasivoPat.setOpaque(false);

        // Panel Pasivos (2)
        JPanel pnlPasivosForm = new JPanel(new BorderLayout(0, 5));
        pnlPasivosForm.setBackground(Color.WHITE);
        pnlPasivosForm.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(239, 68, 68), 2),
                "CÓDIGO 2: PASIVO (Obligaciones)", 0, 0, new Font("Segoe UI", Font.BOLD, 13), new Color(153, 27, 27)),
            BorderFactory.createEmptyBorder(6, 8, 8, 8)
        ));
        modeloPasivos = new DefaultTableModel(new Object[][]{}, new String[]{"Código", "Cuenta", "Categoría", "Saldo ($)"}) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblPasivosForm = new JTable(modeloPasivos);
        tblPasivosForm.setRowHeight(24);
        tblPasivosForm.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        tblPasivosForm.getTableHeader().setBackground(new Color(30, 41, 59));
        tblPasivosForm.getTableHeader().setForeground(Color.WHITE);
        pnlPasivosForm.add(new JScrollPane(tblPasivosForm), BorderLayout.CENTER);

        // Panel Patrimonio (3)
        JPanel pnlPatrimonioForm = new JPanel(new BorderLayout(0, 5));
        pnlPatrimonioForm.setBackground(Color.WHITE);
        pnlPatrimonioForm.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(79, 70, 229), 2),
                "CÓDIGO 3: PATRIMONIO (Capital + Utilidad del Ejercicio)", 0, 0, new Font("Segoe UI", Font.BOLD, 13), new Color(67, 56, 202)),
            BorderFactory.createEmptyBorder(6, 8, 8, 8)
        ));
        modeloPatrimonio = new DefaultTableModel(new Object[][]{}, new String[]{"Código", "Cuenta", "Tipo", "Saldo ($)"}) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblPatrimonioForm = new JTable(modeloPatrimonio);
        tblPatrimonioForm.setRowHeight(24);
        tblPatrimonioForm.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        tblPatrimonioForm.getTableHeader().setBackground(new Color(30, 41, 59));
        tblPatrimonioForm.getTableHeader().setForeground(Color.WHITE);
        pnlPatrimonioForm.add(new JScrollPane(tblPatrimonioForm), BorderLayout.CENTER);

        pnlColPasivoPat.add(pnlPasivosForm);
        pnlColPasivoPat.add(pnlPatrimonioForm);

        pnlGridBalance.add(pnlColActivosForm);
        pnlGridBalance.add(pnlColPasivoPat);

        // Pie de verificación
        JPanel pnlPieBalance = new JPanel(new BorderLayout(10, 8));
        pnlPieBalance.setBackground(Color.WHITE);
        pnlPieBalance.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225)),
            BorderFactory.createEmptyBorder(8, 15, 8, 15)
        ));

        lblTotalPasivoMasPatrimonioForm = new JLabel("TOTAL PASIVO + PATRIMONIO: $0.00", SwingConstants.RIGHT);
        lblTotalPasivoMasPatrimonioForm.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblTotalPasivoMasPatrimonioForm.setForeground(new Color(67, 56, 202));

        lblBannerBalanceForm = new JLabel("VERIFICANDO ECUACIÓN PATRIMONIAL: ACTIVO = PASIVO + PATRIMONIO...", SwingConstants.CENTER);
        lblBannerBalanceForm.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblBannerBalanceForm.setOpaque(true);
        lblBannerBalanceForm.setPreferredSize(new Dimension(700, 32));

        pnlPieBalance.add(lblTotalPasivoMasPatrimonioForm, BorderLayout.NORTH);
        pnlPieBalance.add(lblBannerBalanceForm, BorderLayout.SOUTH);

        pnlTabBalance.add(pnlGridBalance, BorderLayout.CENTER);
        pnlTabBalance.add(pnlPieBalance, BorderLayout.SOUTH);

        tabbedPaneEF.addTab("🏛 Balance General [1 = 2 + 3]", pnlTabBalance);

        // =====================================================================
        // TAB 2: ESTADO DE RESULTADOS (5 - 4 = UTILIDAD)
        // =====================================================================
        JPanel pnlTabResultados = new JPanel(new BorderLayout(0, 10));
        pnlTabResultados.setBackground(new Color(241, 245, 249));
        pnlTabResultados.setBorder(BorderFactory.createEmptyBorder(12, 15, 12, 15));

        modeloResultados = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Concepto", "Parcial", "Total"}
        ) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };

        tblResultadosForm = new JTable(modeloResultados);
        tblResultadosForm.setRowHeight(25);
        tblResultadosForm.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        tblResultadosForm.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tblResultadosForm.getTableHeader().setBackground(new Color(30, 41, 59));
        tblResultadosForm.getTableHeader().setForeground(Color.WHITE);
        tblResultadosForm.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
        tblResultadosForm.getColumnModel().getColumn(2).setCellRenderer(rightRenderer);

        JScrollPane scrollResultadosForm = new JScrollPane(tblResultadosForm);
        scrollResultadosForm.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225)));

        JPanel pnlTarjetaResultados = new JPanel(new GridLayout(2, 4, 15, 10));
        pnlTarjetaResultados.setBackground(Color.WHITE);
        pnlTarjetaResultados.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225)),
            BorderFactory.createEmptyBorder(12, 15, 12, 15)
        ));

        lblVentasNetasForm = new JLabel("Ventas Netas: $0.00");
        lblVentasNetasForm.setFont(new Font("Segoe UI", Font.BOLD, 13));

        lblCostoVentasForm = new JLabel("(-) Costo de Ventas: $0.00");
        lblCostoVentasForm.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblCostoVentasForm.setForeground(new Color(220, 38, 38));

        lblUtilidadBrutaForm = new JLabel("(=) Utilidad Bruta: $0.00");
        lblUtilidadBrutaForm.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblUtilidadBrutaForm.setForeground(new Color(22, 101, 52));

        lblGastosOperacionForm = new JLabel("(-) Gastos Operación: $0.00");
        lblGastosOperacionForm.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblGastosOperacionForm.setForeground(new Color(220, 38, 38));

        lblUtilidadEjercicioForm = new JLabel("(=) Utilidad del ejercicio: $0.00");
        lblUtilidadEjercicioForm.setFont(new Font("Segoe UI", Font.BOLD, 13));

        lblUtilidadNetaForm = new JLabel("(=) UTILIDAD NETA (sin ISR): $0.00");
        lblUtilidadNetaForm.setFont(new Font("Segoe UI", Font.BOLD, 15));
        lblUtilidadNetaForm.setForeground(new Color(79, 70, 229));

        btnRefrescarERForm = new JButton("🔄 Recalcular Reporte");
        btnRefrescarERForm.setBackground(new Color(79, 70, 229));
        btnRefrescarERForm.setForeground(Color.WHITE);
        btnRefrescarERForm.setFont(new Font("Segoe UI", Font.BOLD, 12));

        pnlTarjetaResultados.add(lblVentasNetasForm);
        pnlTarjetaResultados.add(lblCostoVentasForm);
        pnlTarjetaResultados.add(lblUtilidadBrutaForm);
        pnlTarjetaResultados.add(lblGastosOperacionForm);
        pnlTarjetaResultados.add(lblUtilidadEjercicioForm);
        pnlTarjetaResultados.add(lblUtilidadNetaForm);
        pnlTarjetaResultados.add(btnRefrescarERForm);

        pnlTabResultados.add(scrollResultadosForm, BorderLayout.CENTER);
        pnlTabResultados.add(pnlTarjetaResultados, BorderLayout.SOUTH);

        tabbedPaneEF.addTab("📈 Estado de Resultados [5 - 4 = Utilidad]", pnlTabResultados);

        // =========================================================
        // ENSAMBLE FINAL
        // =========================================================
        this.setLayout(new BorderLayout());
        this.setBackground(new Color(241, 245, 249));
        this.add(pnlHeaderEF, BorderLayout.NORTH);
        this.add(tabbedPaneEF, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // =========================================================
    // LÓGICA DE NEGOCIO
    // =========================================================

    public void generarReportes() {
        try {
            // 1. GENERAR ESTADO DE RESULTADOS
            EstadoResultadosResult er = controller.generarEstadoResultados(null);
            modeloResultados.setRowCount(0);

            for (LineaReporte l : er.lineas) {
                boolean enParcial = "PARCIAL".equals(l.getCategoria());
                String monto = String.format("%.2f", l.getSaldo());
                modeloResultados.addRow(new Object[]{
                    l.getNombre(),
                    enParcial ? monto : "",
                    enParcial ? "" : monto
                });
            }
            modeloResultados.addRow(new Object[]{"Nota: No se aplica ISR.", "", ""});

            lblVentasNetasForm.setText("Ventas Netas: $" + String.format("%.2f", er.ventasNetas));
            lblCostoVentasForm.setText("(-) Costo Ventas: $" + String.format("%.2f", er.totalCostos));
            lblUtilidadBrutaForm.setText("(=) Utilidad Bruta: $" + String.format("%.2f", er.utilidadBruta));
            lblGastosOperacionForm.setText("(-) Gastos: $" + String.format("%.2f", er.totalGastos));
            lblUtilidadEjercicioForm.setText("Inventario Final: $" + String.format("%.2f", er.inventarioFinal));
            lblUtilidadNetaForm.setText("(=) UTILIDAD NETA (sin ISR): $" + String.format("%.2f", er.utilidadNeta));

            // 2. GENERAR BALANCE GENERAL (1 = 2 + 3)
            BalanceGeneralResult bg = controller.generarBalanceGeneral(null);
            modeloActivos.setRowCount(0);
            modeloPasivos.setRowCount(0);
            modeloPatrimonio.setRowCount(0);

            for (LineaReporte a : bg.activos) {
                modeloActivos.addRow(new Object[]{a.getCodigo(), a.getNombre(), a.getCategoria(), String.format("%.2f", a.getSaldo())});
            }
            for (LineaReporte p : bg.pasivos) {
                modeloPasivos.addRow(new Object[]{p.getCodigo(), p.getNombre(), p.getCategoria(), String.format("%.2f", p.getSaldo())});
            }
            for (LineaReporte pt : bg.patrimonio) {
                modeloPatrimonio.addRow(new Object[]{pt.getCodigo(), pt.getNombre(), pt.getCategoria(), String.format("%.2f", pt.getSaldo())});
            }

            lblTotalActivoForm.setText("TOTAL ACTIVO: $" + String.format("%.2f", bg.totalActivo));
            lblTotalPasivoMasPatrimonioForm.setText("TOTAL PASIVO ($" + String.format("%.2f", bg.totalPasivo) + ") + PATRIMONIO ($" + String.format("%.2f", bg.totalPatrimonio) + ") = $" + String.format("%.2f", bg.totalPasivoMasPatrimonio));

            if (bg.balanceCuadrado) {
                lblBannerBalanceForm.setText("✔ ECUACIÓN CONTABLE PERFECTA: ACTIVO ($" + String.format("%.2f", bg.totalActivo) + ") = PASIVO + PATRIMONIO ($" + String.format("%.2f", bg.totalPasivoMasPatrimonio) + ")");
                lblBannerBalanceForm.setBackground(new Color(220, 252, 231));
                lblBannerBalanceForm.setForeground(new Color(22, 101, 52));
            } else {
                lblBannerBalanceForm.setText("⚠ DESCUADRE EN EL BALANCE DE $" + String.format("%.2f", bg.diferencia));
                lblBannerBalanceForm.setBackground(new Color(254, 226, 226));
                lblBannerBalanceForm.setForeground(new Color(153, 27, 27));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al generar Estados Financieros: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlHeaderEF;
    private javax.swing.JLabel lblTituloEF;
    private javax.swing.JLabel lblSubtituloEF;
    private javax.swing.JTabbedPane tabbedPaneEF;
    private javax.swing.JTable tblActivosForm;
    private javax.swing.JTable tblPasivosForm;
    private javax.swing.JTable tblPatrimonioForm;
    private javax.swing.JTable tblResultadosForm;
    private javax.swing.JButton btnRefrescarERForm;
    // End of variables declaration//GEN-END:variables
}
