package vistas.FrmAdministrador;

import dao.PartidaDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelos.DetallePartida;
import modelos.MayorCuenta;
import modelos.Usuario;
import vistas.FrmMenuPrincipal;

/**
 * Módulo de Libro Mayor y Mayorización Automática en Tiempo Real.
 * Consolida débitos, créditos y determina automáticamente el saldo
 * (Deudor / Acreedor) de cada cuenta sin cálculos manuales.
 */
public class FrmLibroMayor extends javax.swing.JPanel {

    private final Usuario usuario;
    private final FrmMenuPrincipal menuPrincipal;
    private final PartidaDao partidaDao;

    private List<MayorCuenta> listaMayor = new ArrayList<>();

    // Componentes de la vista (generados por initComponents)
    private JTable tblMayorForm;
    private DefaultTableModel modeloMayor;

    private JTextField txtBuscarMayor;
    private JLabel lblTotalDebitosGlobalForm;
    private JLabel lblTotalCreditosGlobalForm;
    private JLabel lblEstadoBalanceForm;

    // Componentes Cuenta T
    private JComboBox<String> cmbCuentasTForm;
    private JPanel pnlCuentaTContenedorForm;
    private JLabel lblTituloCuentaTForm;
    private DefaultTableModel modeloTDebe;
    private DefaultTableModel modeloTHaber;
    private JTable tblTDebeForm;
    private JTable tblTHaberForm;
    private JLabel lblSubtotalTDebeForm;
    private JLabel lblSubtotalTHaberForm;
    private JLabel lblSaldoFinalTForm;

    // Reference to the tabbed pane for switching tabs on double-click
    private JTabbedPane tabbedPaneMayor;

    public FrmLibroMayor(Usuario usuario, FrmMenuPrincipal menuPrincipal) {
        this.usuario = usuario;
        this.menuPrincipal = menuPrincipal;
        this.partidaDao = new PartidaDao();

        initComponents();
        postInit();
    }

    /**
     * Inicialización post-designer: conecta listeners y carga datos.
     */
    private void postInit() {
        // Conectar listener de botón filtrar
        btnFiltrarMayor.addActionListener(e -> filtrarTabla());
        btnRecalcularMayor.addActionListener(e -> cargarMayorizacion());

        // Doble clic en tabla mayor -> ir a Cuenta T
        tblMayorForm.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int row = tblMayorForm.getSelectedRow();
                    if (row >= 0) {
                        String cod = (String) modeloMayor.getValueAt(row, 0);
                        seleccionarCuentaEnT(cod);
                        tabbedPaneMayor.setSelectedIndex(1);
                    }
                }
            }
        });

        // Listener combo cuenta T
        cmbCuentasTForm.addActionListener(e -> actualizarCuentaT());

        // Estilos adicionales en tiempo de ejecución
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        for (int i = 4; i <= 7; i++) {
            tblMayorForm.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
        }
        tblTDebeForm.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);
        tblTHaberForm.getColumnModel().getColumn(1).setCellRenderer(rightRenderer);

        tblMayorForm.getTableHeader().setBackground(new Color(30, 41, 59));
        tblMayorForm.getTableHeader().setForeground(Color.WHITE);
        tblMayorForm.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));

        cargarMayorizacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // =========================================================
        // ENCABEZADO
        // =========================================================
        pnlHeader = new JPanel(new BorderLayout());
        pnlHeader.setBackground(new Color(30, 41, 59));
        pnlHeader.setBorder(BorderFactory.createEmptyBorder(15, 25, 15, 25));

        JPanel pnlTitulosMayor = new JPanel();
        pnlTitulosMayor.setLayout(new javax.swing.BoxLayout(pnlTitulosMayor, javax.swing.BoxLayout.Y_AXIS));
        pnlTitulosMayor.setOpaque(false);

        lblTituloMayor = new JLabel("LIBRO MAYOR (MAYORIZACIÓN EN TIEMPO REAL)");
        lblTituloMayor.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblTituloMayor.setForeground(Color.WHITE);

        lblSubtituloMayor = new JLabel("Consolidación automática de débitos, créditos y saldos (Deudor / Acreedor)");
        lblSubtituloMayor.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblSubtituloMayor.setForeground(new Color(203, 213, 225));

        pnlTitulosMayor.add(lblTituloMayor);
        pnlTitulosMayor.add(javax.swing.Box.createVerticalStrut(4));
        pnlTitulosMayor.add(lblSubtituloMayor);
        pnlHeader.add(pnlTitulosMayor, BorderLayout.WEST);

        // =========================================================
        // TABS
        // =========================================================
        tabbedPaneMayor = new JTabbedPane();
        tabbedPaneMayor.setFont(new Font("Segoe UI", Font.BOLD, 13));

        // ---- TAB 1: CONSOLIDADO ----
        JPanel pnlTabConsolidado = new JPanel(new BorderLayout(0, 10));
        pnlTabConsolidado.setBackground(new Color(241, 245, 249));
        pnlTabConsolidado.setBorder(BorderFactory.createEmptyBorder(12, 15, 12, 15));

        JPanel pnlBarraBusqueda = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 5));
        pnlBarraBusqueda.setBackground(Color.WHITE);
        pnlBarraBusqueda.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225)),
            BorderFactory.createEmptyBorder(6, 10, 6, 10)
        ));

        txtBuscarMayor = new JTextField(25);
        txtBuscarMayor.setPreferredSize(new Dimension(250, 30));
        txtBuscarMayor.putClientProperty("JTextField.placeholderText", "Buscar por código o nombre...");

        btnFiltrarMayor = new JButton("🔍 Filtrar");
        btnFiltrarMayor.setBackground(new Color(79, 70, 229));
        btnFiltrarMayor.setForeground(Color.WHITE);
        btnFiltrarMayor.setFont(new Font("Segoe UI", Font.BOLD, 12));

        btnRecalcularMayor = new JButton("🔄 Recalcular en Tiempo Real");
        btnRecalcularMayor.setBackground(new Color(34, 197, 94));
        btnRecalcularMayor.setForeground(Color.WHITE);
        btnRecalcularMayor.setFont(new Font("Segoe UI", Font.BOLD, 12));

        pnlBarraBusqueda.add(new JLabel("Filtrar cuenta:"));
        pnlBarraBusqueda.add(txtBuscarMayor);
        pnlBarraBusqueda.add(btnFiltrarMayor);
        pnlBarraBusqueda.add(btnRecalcularMayor);

        // Tabla de mayorización
        modeloMayor = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Código", "Nombre de Cuenta", "Tipo", "Naturaleza", "Total Debe ($)", "Total Haber ($)", "Saldo Deudor ($)", "Saldo Acreedor ($)"}
        ) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };

        tblMayorForm = new JTable(modeloMayor);
        tblMayorForm.setRowHeight(26);
        tblMayorForm.setFont(new Font("Segoe UI", Font.PLAIN, 12));

        JScrollPane scrollPaneMayor = new JScrollPane(tblMayorForm);
        scrollPaneMayor.setBorder(BorderFactory.createLineBorder(new Color(203, 213, 225)));

        // Pie con totales
        JPanel pnlPieMayor = new JPanel(new BorderLayout(10, 5));
        pnlPieMayor.setBackground(Color.WHITE);
        pnlPieMayor.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225)),
            BorderFactory.createEmptyBorder(10, 15, 10, 15)
        ));

        JPanel pnlTotalesMayor = new JPanel(new FlowLayout(FlowLayout.RIGHT, 25, 5));
        pnlTotalesMayor.setOpaque(false);

        lblTotalDebitosGlobalForm = new JLabel("Sumas Débitos: $0.00");
        lblTotalDebitosGlobalForm.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblTotalDebitosGlobalForm.setForeground(new Color(30, 41, 59));

        lblTotalCreditosGlobalForm = new JLabel("Sumas Créditos: $0.00");
        lblTotalCreditosGlobalForm.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblTotalCreditosGlobalForm.setForeground(new Color(30, 41, 59));

        pnlTotalesMayor.add(lblTotalDebitosGlobalForm);
        pnlTotalesMayor.add(lblTotalCreditosGlobalForm);

        lblEstadoBalanceForm = new JLabel("ESTADO DE SUMAS IGUALES: VERIFICANDO...", SwingConstants.CENTER);
        lblEstadoBalanceForm.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblEstadoBalanceForm.setOpaque(true);
        lblEstadoBalanceForm.setPreferredSize(new Dimension(500, 30));

        pnlPieMayor.add(pnlTotalesMayor, BorderLayout.NORTH);
        pnlPieMayor.add(lblEstadoBalanceForm, BorderLayout.SOUTH);

        pnlTabConsolidado.add(pnlBarraBusqueda, BorderLayout.NORTH);
        pnlTabConsolidado.add(scrollPaneMayor, BorderLayout.CENTER);
        pnlTabConsolidado.add(pnlPieMayor, BorderLayout.SOUTH);

        tabbedPaneMayor.addTab("📊 Resumen Consolidado (Balance de Comprobación)", pnlTabConsolidado);

        // ---- TAB 2: CUENTA T ----
        JPanel pnlTabCuentaT = new JPanel(new BorderLayout(0, 10));
        pnlTabCuentaT.setBackground(new Color(241, 245, 249));
        pnlTabCuentaT.setBorder(BorderFactory.createEmptyBorder(12, 15, 12, 15));

        JPanel pnlSelectorCuentaT = new JPanel(new FlowLayout(FlowLayout.LEFT, 15, 8));
        pnlSelectorCuentaT.setBackground(Color.WHITE);
        pnlSelectorCuentaT.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(203, 213, 225)),
            BorderFactory.createEmptyBorder(6, 10, 6, 10)
        ));

        cmbCuentasTForm = new JComboBox<>();
        cmbCuentasTForm.setPreferredSize(new Dimension(450, 30));

        pnlSelectorCuentaT.add(new JLabel("Seleccione Cuenta para ver su esquema en T:"));
        pnlSelectorCuentaT.add(cmbCuentasTForm);

        pnlCuentaTContenedorForm = new JPanel(new BorderLayout());
        pnlCuentaTContenedorForm.setBackground(Color.WHITE);
        pnlCuentaTContenedorForm.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(79, 70, 229), 2),
            BorderFactory.createEmptyBorder(10, 15, 15, 15)
        ));

        lblTituloCuentaTForm = new JLabel("CUENTA T: SELECCIONE UNA CUENTA", SwingConstants.CENTER);
        lblTituloCuentaTForm.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblTituloCuentaTForm.setForeground(new Color(30, 41, 59));
        lblTituloCuentaTForm.setBorder(BorderFactory.createEmptyBorder(0, 0, 10, 0));

        JPanel pnlColumnasT = new JPanel(new GridLayout(1, 2, 15, 0));
        pnlColumnasT.setOpaque(false);

        // Columna DEBE
        JPanel pnlColDebeT = new JPanel(new BorderLayout(0, 5));
        pnlColDebeT.setBackground(new Color(248, 250, 252));
        pnlColDebeT.setBorder(BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(new Color(34, 197, 94), 2),
            "DEBE (Cargos / Débitos)", 0, 0, new Font("Segoe UI", Font.BOLD, 14), new Color(22, 101, 52)
        ));

        modeloTDebe = new DefaultTableModel(new Object[][]{}, new String[]{"Ref. Partida", "Monto ($)"}) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblTDebeForm = new JTable(modeloTDebe);
        tblTDebeForm.setRowHeight(24);
        JScrollPane scrollDebeT = new JScrollPane(tblTDebeForm);

        lblSubtotalTDebeForm = new JLabel("Subtotal Debe: $0.00", SwingConstants.RIGHT);
        lblSubtotalTDebeForm.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblSubtotalTDebeForm.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 10));

        pnlColDebeT.add(scrollDebeT, BorderLayout.CENTER);
        pnlColDebeT.add(lblSubtotalTDebeForm, BorderLayout.SOUTH);

        // Columna HABER
        JPanel pnlColHaberT = new JPanel(new BorderLayout(0, 5));
        pnlColHaberT.setBackground(new Color(248, 250, 252));
        pnlColHaberT.setBorder(BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(new Color(59, 130, 246), 2),
            "HABER (Abonos / Créditos)", 0, 0, new Font("Segoe UI", Font.BOLD, 14), new Color(30, 58, 138)
        ));

        modeloTHaber = new DefaultTableModel(new Object[][]{}, new String[]{"Ref. Partida", "Monto ($)"}) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblTHaberForm = new JTable(modeloTHaber);
        tblTHaberForm.setRowHeight(24);
        JScrollPane scrollHaberT = new JScrollPane(tblTHaberForm);

        lblSubtotalTHaberForm = new JLabel("Subtotal Haber: $0.00", SwingConstants.RIGHT);
        lblSubtotalTHaberForm.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblSubtotalTHaberForm.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 10));

        pnlColHaberT.add(scrollHaberT, BorderLayout.CENTER);
        pnlColHaberT.add(lblSubtotalTHaberForm, BorderLayout.SOUTH);

        pnlColumnasT.add(pnlColDebeT);
        pnlColumnasT.add(pnlColHaberT);

        JPanel pnlFooterT = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10));
        pnlFooterT.setOpaque(false);

        lblSaldoFinalTForm = new JLabel("SALDO DETERMINADO AUTOMÁTICAMENTE: $0.00", SwingConstants.CENTER);
        lblSaldoFinalTForm.setFont(new Font("Segoe UI", Font.BOLD, 15));
        lblSaldoFinalTForm.setOpaque(true);
        lblSaldoFinalTForm.setPreferredSize(new Dimension(650, 36));
        pnlFooterT.add(lblSaldoFinalTForm);

        pnlCuentaTContenedorForm.add(lblTituloCuentaTForm, BorderLayout.NORTH);
        pnlCuentaTContenedorForm.add(pnlColumnasT, BorderLayout.CENTER);
        pnlCuentaTContenedorForm.add(pnlFooterT, BorderLayout.SOUTH);

        pnlTabCuentaT.add(pnlSelectorCuentaT, BorderLayout.NORTH);
        pnlTabCuentaT.add(pnlCuentaTContenedorForm, BorderLayout.CENTER);

        tabbedPaneMayor.addTab("⚖ Esquema Gráfico en Cuenta T", pnlTabCuentaT);

        // =========================================================
        // ENSAMBLE FINAL
        // =========================================================
        this.setLayout(new BorderLayout());
        this.setBackground(new Color(241, 245, 249));
        this.add(pnlHeader, BorderLayout.NORTH);
        this.add(tabbedPaneMayor, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // =========================================================
    // LÓGICA DE NEGOCIO
    // =========================================================

    public void cargarMayorizacion() {
        modeloMayor.setRowCount(0);
        cmbCuentasTForm.removeAllItems();

        try {
            listaMayor = partidaDao.obtenerMayorizacion(null);
            double sumaDebitos = 0.0;
            double sumaCreditos = 0.0;

            for (MayorCuenta mc : listaMayor) {
                sumaDebitos += mc.getTotalDebe();
                sumaCreditos += mc.getTotalHaber();

                modeloMayor.addRow(new Object[]{
                    mc.getCodigo(),
                    mc.getNombre(),
                    mc.getTipo(),
                    mc.getNaturaleza(),
                    String.format("%.2f", mc.getTotalDebe()),
                    String.format("%.2f", mc.getTotalHaber()),
                    String.format("%.2f", mc.getSaldoDeudor()),
                    String.format("%.2f", mc.getSaldoAcreedor())
                });

                cmbCuentasTForm.addItem(mc.getCodigo() + " - " + mc.getNombre());
            }

            lblTotalDebitosGlobalForm.setText("Sumas Débitos: $" + String.format("%.2f", sumaDebitos));
            lblTotalCreditosGlobalForm.setText("Sumas Créditos: $" + String.format("%.2f", sumaCreditos));

            if (Math.abs(sumaDebitos - sumaCreditos) < 0.01 && sumaDebitos > 0) {
                lblEstadoBalanceForm.setText("✔ SUMAS IGUALES CONFIRMADAS (BALANCE DE COMPROBACIÓN CUADRADO: $" + String.format("%.2f", sumaDebitos) + ")");
                lblEstadoBalanceForm.setBackground(new Color(220, 252, 231));
                lblEstadoBalanceForm.setForeground(new Color(22, 101, 52));
            } else {
                lblEstadoBalanceForm.setText("⚠ ATENCIÓN: EXISTE DIFERENCIA EN LAS SUMAS DE $" + String.format("%.2f", Math.abs(sumaDebitos - sumaCreditos)));
                lblEstadoBalanceForm.setBackground(new Color(254, 226, 226));
                lblEstadoBalanceForm.setForeground(new Color(153, 27, 27));
            }

            if (cmbCuentasTForm.getItemCount() > 0) {
                cmbCuentasTForm.setSelectedIndex(0);
                actualizarCuentaT();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al generar mayorización: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void filtrarTabla() {
        String query = txtBuscarMayor.getText().trim().toLowerCase();
        modeloMayor.setRowCount(0);
        for (MayorCuenta mc : listaMayor) {
            if (query.isEmpty() || mc.getCodigo().toLowerCase().contains(query) || mc.getNombre().toLowerCase().contains(query)) {
                modeloMayor.addRow(new Object[]{
                    mc.getCodigo(),
                    mc.getNombre(),
                    mc.getTipo(),
                    mc.getNaturaleza(),
                    String.format("%.2f", mc.getTotalDebe()),
                    String.format("%.2f", mc.getTotalHaber()),
                    String.format("%.2f", mc.getSaldoDeudor()),
                    String.format("%.2f", mc.getSaldoAcreedor())
                });
            }
        }
    }

    private void seleccionarCuentaEnT(String codigo) {
        for (int i = 0; i < cmbCuentasTForm.getItemCount(); i++) {
            if (cmbCuentasTForm.getItemAt(i).startsWith(codigo)) {
                cmbCuentasTForm.setSelectedIndex(i);
                break;
            }
        }
    }

    private void actualizarCuentaT() {
        int idx = cmbCuentasTForm.getSelectedIndex();
        if (idx < 0 || idx >= listaMayor.size()) return;

        MayorCuenta mc = listaMayor.get(idx);
        lblTituloCuentaTForm.setText("CUENTA: " + mc.getCodigo() + " - " + mc.getNombre().toUpperCase() + " (" + mc.getNaturaleza() + ")");

        modeloTDebe.setRowCount(0);
        modeloTHaber.setRowCount(0);

        try {
            List<DetallePartida> movimientos = partidaDao.obtenerMovimientosCuenta(mc.getIdCuenta(), null);
            double sumaD = 0;
            double sumaH = 0;

            for (DetallePartida mov : movimientos) {
                if (mov.getDebe() > 0) {
                    modeloTDebe.addRow(new Object[]{mov.getConcepto(), String.format("%.2f", mov.getDebe())});
                    sumaD += mov.getDebe();
                }
                if (mov.getHaber() > 0) {
                    modeloTHaber.addRow(new Object[]{mov.getConcepto(), String.format("%.2f", mov.getHaber())});
                    sumaH += mov.getHaber();
                }
            }

            lblSubtotalTDebeForm.setText("Subtotal Débitos: $" + String.format("%.2f", sumaD));
            lblSubtotalTHaberForm.setText("Subtotal Créditos: $" + String.format("%.2f", sumaH));

            if (mc.getSaldoDeudor() > 0) {
                lblSaldoFinalTForm.setText("SALDO DEUDOR (DEBE > HABER): $" + String.format("%.2f", mc.getSaldoDeudor()));
                lblSaldoFinalTForm.setBackground(new Color(220, 252, 231));
                lblSaldoFinalTForm.setForeground(new Color(22, 101, 52));
            } else if (mc.getSaldoAcreedor() > 0) {
                lblSaldoFinalTForm.setText("SALDO ACREEDOR (HABER > DEBE): $" + String.format("%.2f", mc.getSaldoAcreedor()));
                lblSaldoFinalTForm.setBackground(new Color(219, 234, 254));
                lblSaldoFinalTForm.setForeground(new Color(30, 64, 175));
            } else {
                lblSaldoFinalTForm.setText("CUENTA SALDADA: $0.00");
                lblSaldoFinalTForm.setBackground(new Color(241, 245, 249));
                lblSaldoFinalTForm.setForeground(new Color(71, 85, 105));
            }

        } catch (SQLException e) {
            System.err.println("Error al cargar T: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JLabel lblTituloMayor;
    private javax.swing.JLabel lblSubtituloMayor;
    private javax.swing.JButton btnFiltrarMayor;
    private javax.swing.JButton btnRecalcularMayor;
    // End of variables declaration//GEN-END:variables
}
