/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.FrmAdministrador;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import modelos.Empresa;
import modelos.Usuario;
import vistas.FrmMenuPrincipal;
import controladores.EmpresaController;
import controladores.PeriodoContableController;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.PeriodoContable;

/**
 *
 * @author Nehemias Valencia
 */
public class FrmPeriodos extends javax.swing.JPanel {

    private PeriodoContableController controlador;
    private EmpresaController empresaController;

    private PeriodoContable periodoSeleccionado = null;

    private final DateTimeFormatter FORMATO_FECHA
            = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    /**
     * Creates new form FrmPeriodos
     */
    public FrmPeriodos(Usuario usuario, FrmMenuPrincipal menuPrincipal) {
        initComponents();
        initializeComponents();

        try {
            controlador = new PeriodoContableController();
            empresaController = new EmpresaController();

            cargarEmpresas();
            cargarPeriodos();
            prepararNuevo();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al conectar con la base de datos:\n"
                    + e.getMessage(),
                    "Error de conexión",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        cmbEmpresa = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeriodos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        dateFechaInicio = new com.toedter.calendar.JDateChooser();
        dateFechaFin = new com.toedter.calendar.JDateChooser();

        setName(""); // NOI18N

        btnNuevo.setText("NUEVO");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("PERIODOS CONTABLES");

        lblEmpresa.setText("Empresa:");

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblPeriodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPeriodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeriodosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeriodos);

        jLabel1.setText("jLabel1");

        lblNombre.setText("Nombre:");

        lblFechaInicio.setText("Fecha Inicio:");

        lblFechaFin.setText("Fecha Fin:");

        lblEstado.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abierto", "Cerrado" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lblTitulo)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(cmbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNombre)
                                        .addComponent(lblEmpresa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFechaFin)
                                            .addComponent(lblFechaInicio)
                                            .addComponent(lblEstado))))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa)
                    .addComponent(cmbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaInicio)
                    .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaFin)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (cmbEmpresa.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar una empresa.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            if (txtNombre.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Debe ingresar el nombre del período.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            if (dateFechaInicio.getDate() == null
                    || dateFechaFin.getDate() == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar la fecha de inicio y la fecha de finalización.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            LocalDate fechaInicio = dateFechaInicio.getDate()
                    .toInstant()
                    .atZone(java.time.ZoneId.systemDefault())
                    .toLocalDate();

            LocalDate fechaFin = dateFechaFin.getDate()
                    .toInstant()
                    .atZone(java.time.ZoneId.systemDefault())
                    .toLocalDate();

            if (fechaFin.isBefore(fechaInicio)) {
                JOptionPane.showMessageDialog(
                        this,
                        "La fecha de finalización no puede ser anterior a la fecha de inicio.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            Empresa empresa = (Empresa) cmbEmpresa.getSelectedItem();

            String nombre = txtNombre.getText().trim();
            String estado = cmbEstado.getSelectedItem().toString().toUpperCase();

            PeriodoContable periodo = new PeriodoContable();

            periodo.setIdEmpresa(empresa.getIdEmpresa());
            periodo.setNombre(nombre);
            periodo.setFechaInicio(fechaInicio);
            periodo.setFechaFin(fechaFin);
            periodo.setEstado(estado);

            controlador.insertar(periodo);

            JOptionPane.showMessageDialog(
                    this,
                    "Período contable guardado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );

            cargarPeriodos();
            prepararNuevo();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al guardar el período:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ocurrió un error:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if (periodoSeleccionado == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe seleccionar un período de la tabla para modificar.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {

            if (cmbEmpresa.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar una empresa.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                cmbEmpresa.requestFocus();
                return;
            }

            Empresa empresa = (Empresa) cmbEmpresa.getSelectedItem();

            String nombre = txtNombre.getText().trim();

            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "El nombre del período es obligatorio.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                txtNombre.requestFocus();
                return;
            }

            if (dateFechaInicio.getDate() == null
                    || dateFechaFin.getDate() == null) {

                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar la fecha de inicio y la fecha de finalización.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            LocalDate fechaInicio = dateFechaInicio.getDate()
                    .toInstant()
                    .atZone(java.time.ZoneId.systemDefault())
                    .toLocalDate();

            LocalDate fechaFin = dateFechaFin.getDate()
                    .toInstant()
                    .atZone(java.time.ZoneId.systemDefault())
                    .toLocalDate();

            if (fechaFin.isBefore(fechaInicio)) {
                JOptionPane.showMessageDialog(
                        this,
                        "La fecha de finalización no puede ser anterior a la fecha de inicio.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            if (cmbEstado.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar el estado del período.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            periodoSeleccionado.setIdEmpresa(empresa.getIdEmpresa());
            periodoSeleccionado.setNombre(nombre);
            periodoSeleccionado.setFechaInicio(fechaInicio);
            periodoSeleccionado.setFechaFin(fechaFin);

            String estado = cmbEstado.getSelectedItem()
                    .toString()
                    .toUpperCase();

            periodoSeleccionado.setEstado(estado);

            controlador.actualizar(periodoSeleccionado);

            JOptionPane.showMessageDialog(
                    this,
                    "Período contable modificado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );

            prepararNuevo();
            cargarPeriodos();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al modificar el período:\n" + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void limpiarCampos() {

        cmbEmpresa.setSelectedIndex(-1);

        txtNombre.setText("");

        dateFechaInicio.setDate(null);
        dateFechaFin.setDate(null);

        cmbEstado.setSelectedIndex(-1);

        periodoSeleccionado = null;

        tblPeriodos.clearSelection();
    }

    private void tblPeriodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeriodosMouseClicked
        int fila = tblPeriodos.getSelectedRow();

        if (fila == -1) {
            return;
        }

        try {

            int idPeriodo
                    = Integer.parseInt(
                            tblPeriodos.getValueAt(fila, 0).toString()
                    );

            periodoSeleccionado
                    = controlador.buscarPorId(idPeriodo);

            if (periodoSeleccionado == null) {
                return;
            }

            // Buscar empresa correspondiente
            for (int i = 0; i < cmbEmpresa.getItemCount(); i++) {

                Empresa empresa = cmbEmpresa.getItemAt(i);

                if (empresa.getIdEmpresa()
                        == periodoSeleccionado.getIdEmpresa()) {

                    cmbEmpresa.setSelectedIndex(i);
                    break;
                }
            }

            txtNombre.setText(
                    periodoSeleccionado.getNombre()
            );

            dateFechaInicio.setDate(
                    java.sql.Date.valueOf(
                            periodoSeleccionado.getFechaInicio()
                    )
            );

            dateFechaFin.setDate(
                    java.sql.Date.valueOf(
                            periodoSeleccionado.getFechaFin()
                    )
            );
            
            String estado = periodoSeleccionado.getEstado();

            if (estado != null) {
                estado = estado.substring(0, 1).toUpperCase()
                        + estado.substring(1).toLowerCase();
            }

            cmbEstado.setSelectedItem(estado);

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al seleccionar el período:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_tblPeriodosMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void prepararNuevo() {

        periodoSeleccionado = null;

        txtNombre.setText("");
        dateFechaInicio.setDate(null);
        dateFechaFin.setDate(null);

        if (cmbEstado.getItemCount() > 0) {
            cmbEstado.setSelectedItem("Abierto");
        }

        tblPeriodos.clearSelection();

        txtNombre.requestFocus();
    }

    private void cargarEmpresas() {

        try {

            cmbEmpresa.removeAllItems();

            List<Empresa> empresas = empresaController.listar();

            for (Empresa empresa : empresas) {
                cmbEmpresa.addItem(empresa);
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar las empresas:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void cargarPeriodos() {

        try {

            List<PeriodoContable> periodos = controlador.listar();

            llenarTabla(periodos);

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al cargar los períodos:\n"
                    + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private void llenarTabla(List<PeriodoContable> periodos) {

        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "ID",
                    "Empresa",
                    "Nombre",
                    "Fecha inicio",
                    "Fecha fin",
                    "Estado"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (PeriodoContable periodo : periodos) {

            String estado;

            if (periodo.getEstado().equals("ABIERTO")) {
                estado = "Abierto";
            } else {
                estado = "Cerrado";
            }

            modelo.addRow(new Object[]{
                periodo.getIdPeriodo(),
                periodo.getIdEmpresa(),
                periodo.getNombre(),
                periodo.getFechaInicio(),
                periodo.getFechaFin(),
                estado
            });
        }

        tblPeriodos.setModel(modelo);
    }

    private void initializeComponents() {

        // ============================================================
        // 1. ENCABEZADO
        // ============================================================
        JPanel pnlHeader = new JPanel(new java.awt.BorderLayout());
        pnlHeader.setBackground(new Color(15, 23, 42)); // Slate 900
        pnlHeader.setPreferredSize(new Dimension(1050, 60));
        pnlHeader.setBorder(
                BorderFactory.createEmptyBorder(0, 25, 0, 25)
        );

        jLabel1.setText("PERÍODOS CONTABLES");
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 20));
        jLabel1.setForeground(Color.WHITE);

        pnlHeader.add(jLabel1, java.awt.BorderLayout.CENTER);

        this.setLayout(new java.awt.BorderLayout());
        this.add(pnlHeader, java.awt.BorderLayout.NORTH);

        // ============================================================
        // 2. CONTENEDOR PRINCIPAL
        // ============================================================
        JPanel pnlMain = new JPanel(
                new java.awt.BorderLayout(0, 20)
        );

        pnlMain.setBackground(new Color(241, 245, 249));

        pnlMain.setBorder(
                BorderFactory.createEmptyBorder(
                        20, 25, 20, 25
                )
        );

        this.add(
                pnlMain,
                java.awt.BorderLayout.CENTER
        );

        // ============================================================
        // 3. FORMULARIO
        // ============================================================
        JPanel pnlForm = new JPanel(
                new java.awt.GridBagLayout()
        );

        pnlForm.setBackground(Color.WHITE);

        pnlForm.setBorder(
                BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(
                                new Color(226, 232, 240), 1
                        ),
                        BorderFactory.createEmptyBorder(
                                20, 25, 20, 25
                        )
                )
        );

        // ============================================================
        // 4. CONFIGURACIÓN GENERAL
        // ============================================================
        java.awt.GridBagConstraints gbc
                = new java.awt.GridBagConstraints();

        gbc.insets
                = new java.awt.Insets(8, 10, 8, 10);

        gbc.fill
                = java.awt.GridBagConstraints.HORIZONTAL;

        // Fuentes
        Font fontLabel
                = new Font("Segoe UI", Font.BOLD, 13);

        Font fontInput
                = new Font("Segoe UI", Font.PLAIN, 14);

        // Colores
        Color colorLabel
                = new Color(71, 85, 105);

        Color colorBgInput
                = new Color(248, 250, 252);

        // Bordes de los campos
        javax.swing.border.Border borderInput
                = BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(
                                new Color(203, 213, 225), 1
                        ),
                        BorderFactory.createEmptyBorder(
                                6, 10, 6, 10
                        )
                );

        // ============================================================
        // 5. TEXTOS DE LAS ETIQUETAS
        // ============================================================
        lblEmpresa.setText("Empresa:");
        lblNombre.setText("Nombre del período:");
        lblFechaInicio.setText("Fecha de inicio:");
        lblFechaFin.setText("Fecha de finalización:");
        lblEstado.setText("Estado:");

        // ============================================================
        // 6. ESTILO DE LAS ETIQUETAS
        // ============================================================
        JLabel[] labels = {
            lblEmpresa,
            lblNombre,
            lblFechaInicio,
            lblFechaFin,
            lblEstado
        };

        for (JLabel lbl : labels) {

            lbl.setFont(fontLabel);
            lbl.setForeground(colorLabel);

        }

        // ============================================================
        // 7. ESTILO DE LOS CAMPOS
        // ============================================================
        Dimension dimInput
                = new Dimension(220, 38);

        JComponent[] inputs = {
            cmbEmpresa,
            txtNombre,
            dateFechaInicio,
            dateFechaFin,
            cmbEstado

        };

        for (JComponent input : inputs) {

            input.setFont(fontInput);

            input.setBackground(colorBgInput);

            input.setPreferredSize(dimInput);

            if (input instanceof JTextField) {

                input.setBorder(borderInput);

            }

        }

        // ============================================================
        // 8. CONFIGURAR COMBOBOX
        // ============================================================
        cmbEmpresa.setFont(fontInput);

        cmbEmpresa.setBackground(colorBgInput);

        cmbEstado.setFont(fontInput);

        cmbEstado.setBackground(colorBgInput);

        // ============================================================
        // 9. DISTRIBUCIÓN DEL FORMULARIO
        // ============================================================
        // ------------------------------------------------------------
        // FILA 0
        // Empresa
        // Nombre
        // ------------------------------------------------------------
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.0;

        pnlForm.add(
                lblEmpresa,
                gbc
        );

        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;

        pnlForm.add(
                cmbEmpresa,
                gbc
        );

        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.0;

        pnlForm.add(
                lblNombre,
                gbc
        );

        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 0.5;

        pnlForm.add(
                txtNombre,
                gbc
        );

        // ------------------------------------------------------------
        // FILA 1
        // Fecha inicio
        // Fecha fin
        // ------------------------------------------------------------
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.0;

        pnlForm.add(
                lblFechaInicio,
                gbc
        );

        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.5;

        pnlForm.add(dateFechaInicio,
                gbc
        );

        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 0.0;

        pnlForm.add(
                lblFechaFin,
                gbc
        );

        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 0.5;

        pnlForm.add(dateFechaFin,
                gbc
        );

        // ------------------------------------------------------------
        // FILA 2
        // Estado
        // ------------------------------------------------------------
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.0;

        pnlForm.add(
                lblEstado,
                gbc
        );

        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 0.5;

        pnlForm.add(
                cmbEstado,
                gbc
        );

        // ============================================================
        // 10. BOTONES
        // ============================================================
        JPanel pnlBotones
                = new JPanel(
                        new java.awt.FlowLayout(
                                java.awt.FlowLayout.RIGHT,
                                10,
                                0
                        )
                );

        pnlBotones.setOpaque(false);

        // Botón Nuevo
        estilarBoton(
                btnNuevo,
                "Nuevo",
                new Color(241, 245, 249),
                new Color(30, 41, 59),
                new Color(203, 213, 225)
        );

        // Botón Guardar
        estilarBoton(
                btnGuardar,
                "Guardar",
                new Color(37, 99, 235),
                Color.WHITE,
                new Color(29, 78, 216)
        );

        // Botón Editar
        estilarBoton(
                btnModificar,
                "Editar",
                new Color(217, 119, 6),
                Color.WHITE,
                new Color(180, 83, 9)
        );

        pnlBotones.add(btnNuevo);
        pnlBotones.add(btnGuardar);
        pnlBotones.add(btnModificar);

        // ------------------------------------------------------------
        // Agregar botones debajo de los campos
        // ------------------------------------------------------------
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;

        gbc.insets
                = new java.awt.Insets(
                        18, 0, 0, 0
                );

        pnlForm.add(
                pnlBotones,
                gbc
        );

        // Agregar formulario al panel principal
        pnlMain.add(
                pnlForm,
                java.awt.BorderLayout.NORTH
        );

        // ============================================================
        // 11. SECCIÓN DE BÚSQUEDA Y TABLA
        // ============================================================
        JPanel pnlTablaContainer
                = new JPanel(
                        new java.awt.BorderLayout(
                                0, 12
                        )
                );

        pnlTablaContainer.setOpaque(false);

        // ============================================================
        // 13. CONFIGURACIÓN DE LA TABLA
        // ============================================================
        tblPeriodos.setFont(
                new Font(
                        "Segoe UI",
                        Font.PLAIN,
                        13
                )
        );

        tblPeriodos.setRowHeight(36);

        tblPeriodos.setSelectionBackground(
                new Color(224, 242, 254)
        );

        tblPeriodos.setSelectionForeground(
                new Color(15, 23, 42)
        );

        tblPeriodos.setShowVerticalLines(false);

        tblPeriodos.setGridColor(
                new Color(226, 232, 240)
        );

        // ============================================================
        // 14. ENCABEZADO DE LA TABLA
        // ============================================================
        javax.swing.table.JTableHeader header
                = tblPeriodos.getTableHeader();

        header.setFont(
                new Font(
                        "Segoe UI",
                        Font.BOLD,
                        12
                )
        );

        header.setBackground(
                new Color(241, 245, 249)
        );

        header.setForeground(
                new Color(71, 85, 105)
        );

        header.setPreferredSize(
                new Dimension(
                        0,
                        38
                )
        );

        // ============================================================
        // 15. SCROLL DE LA TABLA
        // ============================================================
        jScrollPane1.setViewportView(
                tblPeriodos
        );

        jScrollPane1.setBorder(
                BorderFactory.createLineBorder(
                        new Color(226, 232, 240),
                        1
                )
        );

        jScrollPane1.getViewport()
                .setBackground(Color.WHITE);

        pnlTablaContainer.add(
                jScrollPane1,
                java.awt.BorderLayout.CENTER
        );

        // Agregar tabla al panel principal
        pnlMain.add(
                pnlTablaContainer,
                java.awt.BorderLayout.CENTER
        );
    }

    private void estilarBoton(
            JButton btn,
            String texto,
            Color bg,
            Color fg,
            Color borderColor) {

        btn.setText(texto);

        btn.setFont(
                new Font(
                        "Segoe UI",
                        Font.BOLD,
                        13
                )
        );

        btn.setBackground(bg);

        btn.setForeground(fg);

        btn.setFocusPainted(false);

        btn.setCursor(
                new Cursor(
                        Cursor.HAND_CURSOR
                )
        );

        btn.setPreferredSize(
                new Dimension(
                        110,
                        38
                )
        );

        btn.setBorder(
                BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(
                                borderColor,
                                1,
                                true
                        ),
                        BorderFactory.createEmptyBorder(
                                4,
                                10,
                                4,
                                10
                        )
                )
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<Empresa> cmbEmpresa;
    private javax.swing.JComboBox<String> cmbEstado;
    private com.toedter.calendar.JDateChooser dateFechaFin;
    private com.toedter.calendar.JDateChooser dateFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblPeriodos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
