/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.FrmAdministrador;

import controladores.ProductoController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import modelos.Usuario;
import vistas.FrmMenuPrincipal;



/**
 *
 * @author maril
 */



public class FrmProductos extends javax.swing.JPanel {

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos(Usuario usuario, FrmMenuPrincipal menuPrincipal) {
        initComponents();
        initializeComponents();
       
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblUnidadMedida = new javax.swing.JLabel();
        cmbUnidadMedida = new javax.swing.JComboBox<>();
        lblPrecioCompra = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        lblPrecioVenta = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        lblStockMinimo = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        lblExistencia = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        cmbEstado = new javax.swing.JComboBox<>();

        jLabel1.setText("PERIODOS CONTABLES");

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("PRODUCTOS");

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCodigo.setText(" Código: ");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripción: ");

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        lblUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUnidadMedida.setText(" Unidad medida: ");

        cmbUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidad", "Caja", "Paquete", "Docena", "Kilogramo", "Gramo", "Litro", "Metro" }));

        lblPrecioCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecioCompra.setText("Precio compra: ");

        lblPrecioVenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecioVenta.setText("Precio venta: ");

        lblStockMinimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStockMinimo.setText(" Stock mínimo: ");

        lblExistencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExistencia.setText("Existencia:");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setText(" Estado:  ");

        btnGuardar.setText("GUARDAR");

        btnModificar.setText("MODIFICAR");

        btnDesactivar.setText("DESACTIVAR");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUnidadMedida)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblDescripcion)
                            .addComponent(lblCodigo)))
                    .addComponent(lblPrecioCompra)
                    .addComponent(btnNuevo)
                    .addComponent(lblExistencia)
                    .addComponent(lblEstado))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtExistencia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbUnidadMedida, javax.swing.GroupLayout.Alignment.LEADING, 0, 118, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecioVenta)
                                    .addComponent(lblStockMinimo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrecioVenta)
                                    .addComponent(txtStockMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDesactivar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnModificar)))))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidadMedida)
                    .addComponent(cmbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrecioVenta)
                        .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockMinimo)
                    .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExistencia))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initializeComponents() {

        // =========================================================
        // FORMULARIO PRINCIPAL
        // =========================================================
        this.setLayout(new BorderLayout(0, 15));
        this.setBackground(new Color(241, 245, 249));

        // =========================================================
        // ENCABEZADO
        // =========================================================
        JPanel pnlHeader = new JPanel(new BorderLayout());
        pnlHeader.setBackground(new Color(15, 23, 42));
        pnlHeader.setBorder(
                BorderFactory.createEmptyBorder(18, 25, 18, 25)
        );

        jLabel1.setText("PRODUCTOS");
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 20));
        jLabel1.setForeground(Color.WHITE);

        pnlHeader.add(jLabel1, BorderLayout.WEST);

        // =========================================================
        // PANEL PRINCIPAL
        // =========================================================
        JPanel pnlMain = new JPanel(new BorderLayout(0, 15));
        pnlMain.setBackground(new Color(241, 245, 249));
        pnlMain.setBorder(
                BorderFactory.createEmptyBorder(0, 20, 20, 20)
        );

        // =========================================================
        // PANEL DE DATOS
        // =========================================================
        JPanel pnlDatos = new JPanel(new GridBagLayout());
        pnlDatos.setBackground(Color.WHITE);
        pnlDatos.setBorder(
                BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(
                                new Color(226, 232, 240)
                        ),
                        BorderFactory.createEmptyBorder(
                                20, 20, 20, 20
                        )
                )
        );

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(7, 10, 7, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;

        // =========================================================
        // ESTILO DE ETIQUETAS
        // =========================================================
        JLabel[] etiquetas = {
            lblCodigo,
            lblNombre,
            lblDescripcion,
            lblUnidadMedida,
            lblPrecioCompra,
            lblPrecioVenta,
            lblExistencia,
            lblStockMinimo,
            lblEstado
        };

        for (JLabel etiqueta : etiquetas) {
            etiqueta.setFont(
                    new Font("Segoe UI", Font.BOLD, 13)
            );
            etiqueta.setForeground(
                    new Color(71, 85, 105)
            );
        }

        // =========================================================
        // ESTILO DE CAMPOS DE TEXTO
        // =========================================================
        JTextField[] campos = {
            txtCodigo,
            txtNombre,
            txtDescripcion,
            txtPrecioCompra,
            txtPrecioVenta,
            txtExistencia,
            txtStockMinimo
        };

        for (JTextField campo : campos) {

            campo.setFont(
                    new Font("Segoe UI", Font.PLAIN, 14)
            );

            campo.setBackground(
                    new Color(248, 250, 252)
            );

            campo.setBorder(
                    BorderFactory.createCompoundBorder(
                            BorderFactory.createLineBorder(
                                    new Color(203, 213, 225)
                            ),
                            BorderFactory.createEmptyBorder(
                                    5, 8, 5, 8
                            )
                    )
            );

            campo.setPreferredSize(
                    new Dimension(220, 38)
            );
        }

        // =========================================================
        // ESTILO DE COMBOS
        // =========================================================
        cmbUnidadMedida.setFont(
                new Font("Segoe UI", Font.PLAIN, 14)
        );

        cmbUnidadMedida.setBackground(Color.WHITE);

        cmbUnidadMedida.setPreferredSize(
                new Dimension(220, 38)
        );

        cmbEstado.setFont(
                new Font("Segoe UI", Font.PLAIN, 14)
        );

        cmbEstado.setBackground(Color.WHITE);

        cmbEstado.setPreferredSize(
                new Dimension(220, 38)
        );

        // =========================================================
        // FILA 1 - CÓDIGO / NOMBRE
        // =========================================================
        gbc.gridx = 0;
        gbc.gridy = 0;
        pnlDatos.add(lblCodigo, gbc);

        gbc.gridx = 1;
        pnlDatos.add(txtCodigo, gbc);

        gbc.gridx = 2;
        pnlDatos.add(lblNombre, gbc);

        gbc.gridx = 3;
        pnlDatos.add(txtNombre, gbc);

        // =========================================================
        // FILA 2 - DESCRIPCIÓN / UNIDAD
        // =========================================================
        gbc.gridx = 0;
        gbc.gridy = 1;
        pnlDatos.add(lblDescripcion, gbc);

        gbc.gridx = 1;
        pnlDatos.add(txtDescripcion, gbc);

        gbc.gridx = 2;
        pnlDatos.add(lblUnidadMedida, gbc);

        gbc.gridx = 3;
        pnlDatos.add(cmbUnidadMedida, gbc);

        // =========================================================
        // FILA 3 - PRECIO COMPRA / PRECIO VENTA
        // =========================================================
        gbc.gridx = 0;
        gbc.gridy = 2;
        pnlDatos.add(lblPrecioCompra, gbc);

        gbc.gridx = 1;
        pnlDatos.add(txtPrecioCompra, gbc);

        gbc.gridx = 2;
        pnlDatos.add(lblPrecioVenta, gbc);

        gbc.gridx = 3;
        pnlDatos.add(txtPrecioVenta, gbc);

        // =========================================================
        // FILA 4 - EXISTENCIA / STOCK MÍNIMO
        // =========================================================
        gbc.gridx = 0;
        gbc.gridy = 3;
        pnlDatos.add(lblExistencia, gbc);

        gbc.gridx = 1;
        pnlDatos.add(txtExistencia, gbc);

        gbc.gridx = 2;
        pnlDatos.add(lblStockMinimo, gbc);

        gbc.gridx = 3;
        pnlDatos.add(txtStockMinimo, gbc);

        // =========================================================
        // FILA 5 - ESTADO
        // =========================================================
        gbc.gridx = 0;
        gbc.gridy = 4;
        pnlDatos.add(lblEstado, gbc);

        gbc.gridx = 1;
        pnlDatos.add(cmbEstado, gbc);

        // =========================================================
        // BOTONES
        // =========================================================
        JPanel pnlBotones = new JPanel(
                new FlowLayout(
                        FlowLayout.LEFT,
                        10,
                        5
                )
        );

        pnlBotones.setBackground(Color.WHITE);

        estilarBoton(btnNuevo, "nuevo");
        estilarBoton(btnGuardar, "guardar");
        estilarBoton(btnModificar, "editar");

        pnlBotones.add(btnNuevo);
        pnlBotones.add(btnGuardar);
        pnlBotones.add(btnModificar);
        pnlBotones.add(btnDesactivar);

        // =========================================================
        // PANEL SUPERIOR: DATOS + BOTONES
        // =========================================================
        JPanel pnlSuperior = new JPanel(
                new BorderLayout(0, 10)
        );

        pnlSuperior.setBackground(
                new Color(241, 245, 249)
        );

        pnlSuperior.add(
                pnlDatos,
                BorderLayout.CENTER
        );

        pnlSuperior.add(
                pnlBotones,
                BorderLayout.SOUTH
        );

        // =========================================================
        // TABLA
        // =========================================================
        tblProductos.setFont(
                new Font("Segoe UI", Font.PLAIN, 13)
        );

        tblProductos.setRowHeight(36);

        tblProductos.setSelectionBackground(
                new Color(224, 242, 254)
        );

        tblProductos.setSelectionForeground(
                new Color(15, 23, 42)
        );

        tblProductos.setShowVerticalLines(false);

        tblProductos.setGridColor(
                new Color(226, 232, 240)
        );

        // CABECERA DE LA TABLA
        tblProductos.getTableHeader().setFont(
                new Font("Segoe UI", Font.BOLD, 12)
        );

        tblProductos.getTableHeader().setBackground(
                new Color(241, 245, 249)
        );

        tblProductos.getTableHeader().setForeground(
                new Color(71, 85, 105)
        );

        tblProductos.getTableHeader().setPreferredSize(
                new Dimension(0, 38)
        );

        // =========================================================
        // PANEL DE TABLA
        // =========================================================
        JPanel pnlTabla = new JPanel(
                new BorderLayout(0, 10)
        );

        pnlTabla.setBackground(Color.WHITE);

        pnlTabla.setBorder(
                BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(
                                new Color(226, 232, 240)
                        ),
                        BorderFactory.createEmptyBorder(
                                10, 10, 10, 10
                        )
                )
        );

        /*
     * IMPORTANTE:
     * Aquí NO pongo jScrollPane3 porque no sabemos
     * cómo se llama tu JScrollPane.
     *
     * Si el JScrollPane se llama jScrollPane1,
     * entonces usa:
     *
     * pnlTabla.add(jScrollPane1, BorderLayout.CENTER);
         */
        // =========================================================
        // AGREGAR TODO AL FORMULARIO
        // =========================================================
        pnlMain.add(
                pnlSuperior,
                BorderLayout.NORTH
        );

        pnlMain.add(
                pnlTabla,
                BorderLayout.CENTER
        );

        this.add(
                pnlHeader,
                BorderLayout.NORTH
        );

        this.add(
                pnlMain,
                BorderLayout.CENTER
        );
    }

    private void estilarBoton(JButton boton, String tipo) {

        boton.setFont(new Font("Segoe UI", Font.BOLD, 13));
        boton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        boton.setPreferredSize(new Dimension(110, 38));

        switch (tipo) {

            case "nuevo":
                boton.setBackground(new Color(241, 245, 249));
                boton.setForeground(new Color(30, 41, 59));
                boton.setBorder(
                        BorderFactory.createLineBorder(
                                new Color(203, 213, 225)
                        )
                );
                break;

            case "guardar":
                boton.setBackground(new Color(37, 99, 235));
                boton.setForeground(Color.WHITE);
                boton.setBorder(
                        BorderFactory.createLineBorder(
                                new Color(29, 78, 216)
                        )
                );
                break;

            case "editar":
                boton.setBackground(new Color(217, 119, 6));
                boton.setForeground(Color.WHITE);
                boton.setBorder(
                        BorderFactory.createLineBorder(
                                new Color(180, 83, 9)
                        )
                );
                break;

            case "limpiar":
                boton.setBackground(new Color(100, 116, 139));
                boton.setForeground(Color.WHITE);
                boton.setBorder(
                        BorderFactory.createLineBorder(
                                new Color(71, 85, 105)
                        )
                );
                break;
        }
    }

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbUnidadMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblExistencia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioCompra;
    private javax.swing.JLabel lblPrecioVenta;
    private javax.swing.JLabel lblStockMinimo;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtStockMinimo;
    // End of variables declaration//GEN-END:variables
}
