/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.UsuarioController;
import dao.usuarioDAO;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import modelos.Usuario;

/**
 *
 * @author Nehemias Valencia
 */
public class FrmLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    private UsuarioController controller;

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();

        controller = new UsuarioController();

        setTitle("Sistema Contable - Iniciar Sesión");
        setSize(400, 400);
        setLocationRelativeTo(null);
        setResizable(false);
        setLayout(null);
        initializeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        pnlInfo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIniciarSesion.setText("Inicar sesion");

        lblUsuario.setText("Usuario:");

        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);

        lblPassword.setText("Contraseña:");

        btnIniciarSesion.setText("Iniciar Session");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        lblMensaje.setText("¿Problemas para entrar?");

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblIniciarSesion))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblMensaje))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnIniciarSesion)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnIniciarSesion)
                .addGap(18, 18, 18)
                .addComponent(lblMensaje)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        lblLogo.setText("Poner logo");

        lblTitulo.setText("SISTEMA CONTABLE ");

        lblDescripcion.setText("Gestión financiera y contable");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblTitulo))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addComponent(lblLogo))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addGap(16, 16, 16)
                .addComponent(lblDescripcion)
                .addGap(18, 18, 18)
                .addComponent(lblLogo)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // Obtener el usuario ingresado
        String nombreUsuario = txtUsuario.getText().trim();

// Obtener la contraseña ingresada
        String password = new String(txtPassword.getPassword());

// Validar que los campos no estén vacíos
        if (nombreUsuario.isEmpty() || password.isEmpty()) {

            lblMensaje.setText("Complete todos los campos.");
            return;
        }

// Intentar iniciar sesión mediante el controlador
        Usuario usuario = controller.iniciarSesion(
                nombreUsuario,
                password
        );

// Verificar si las credenciales son correctas
        if (usuario != null) {

            // Verificar si el usuario está activo
            if (!usuario.isEstado()) {

                lblMensaje.setText("El usuario está inactivo.");

                // Limpiar la contraseña
                txtPassword.setText("");

                // Colocar el cursor nuevamente en el usuario
                txtUsuario.requestFocus();

                return;
            }

            // El usuario está activo, permitir el acceso
            FrmMenuPrincipal frmMenu
                    = new FrmMenuPrincipal(usuario);

            frmMenu.setVisible(true);

            // Cerrar el login
            this.dispose();

        } else {

            // Mostrar mensaje de error
            lblMensaje.setText("Usuario o contraseña incorrectos.");

            // Limpiar la contraseña
            txtPassword.setText("");

            // Colocar el cursor nuevamente en el usuario
            txtUsuario.requestFocus();
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    private void initializeComponents() {
        // Configuración general del JFrame/Ventana principal
        this.setSize(750, 450);
        this.setLayout(null);
        this.getContentPane().setBackground(new Color(241, 245, 249)); // Fondo neutro claro

        // =========================================================================
        // 1. PANEL IZQUIERDO: pnlInfo (Branding / Presentación)
        // =========================================================================
        pnlInfo.setBounds(0, 0, 320, 450);
        pnlInfo.setBackground(new Color(15, 23, 42)); // Azul oscuro elegante (Slate 900)
        pnlInfo.setLayout(null);
        add(pnlInfo);

        // lblLogo: Logotipo o espacio del icono
        lblLogo.setText("LOGO");
        lblLogo.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblLogo.setForeground(new Color(56, 189, 248)); // Azul cyan
        lblLogo.setHorizontalAlignment(SwingConstants.CENTER);
        lblLogo.setBounds(40, 80, 240, 60);
        pnlInfo.add(lblLogo);

        // lblTitulo: Nombre del sistema
        lblTitulo.setText("SISTEMA CONTABLE");
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblTitulo.setForeground(Color.WHITE);
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitulo.setBounds(20, 160, 280, 35);
        pnlInfo.add(lblTitulo);

        // lblDescripcion: Subtítulo
        lblDescripcion.setText("Gestión financiera y contable");
        lblDescripcion.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblDescripcion.setForeground(new Color(148, 163, 184)); // Gris suave
        lblDescripcion.setHorizontalAlignment(SwingConstants.CENTER);
        lblDescripcion.setBounds(20, 200, 280, 25);
        pnlInfo.add(lblDescripcion);

        // =========================================================================
        // 2. PANEL DERECHO: pnlLogin (Formulario de inicio de sesión)
        // =========================================================================
        pnlLogin.setBounds(320, 0, 430, 450);
        pnlLogin.setBackground(Color.WHITE);
        pnlLogin.setLayout(null);
        add(pnlLogin);

        // lblIniciarSesion: Encabezado del formulario
        lblIniciarSesion.setText("Iniciar Sesión");
        lblIniciarSesion.setFont(new Font("Segoe UI", Font.BOLD, 22));
        lblIniciarSesion.setForeground(new Color(30, 41, 59));
        lblIniciarSesion.setBounds(50, 40, 310, 30);
        pnlLogin.add(lblIniciarSesion);

        // lblUsuario: Etiqueta usuario
        lblUsuario.setText("Usuario");
        lblUsuario.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblUsuario.setForeground(new Color(71, 85, 105));
        lblUsuario.setBounds(50, 95, 310, 20);
        pnlLogin.add(lblUsuario);

        // txtUsuario: Campo de texto
        txtUsuario.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txtUsuario.setBackground(new Color(248, 250, 252));
        txtUsuario.setForeground(new Color(15, 23, 42));
        txtUsuario.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(203, 213, 225), 1),
                BorderFactory.createEmptyBorder(5, 10, 5, 10) // Padding interno
        ));
        txtUsuario.setBounds(50, 120, 310, 38);
        pnlLogin.add(txtUsuario);

        // lblPassword: Etiqueta contraseña
        lblPassword.setText("Contraseña");
        lblPassword.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lblPassword.setForeground(new Color(71, 85, 105));
        lblPassword.setBounds(50, 175, 310, 20);
        pnlLogin.add(lblPassword);

        // txtPassword: Campo de contraseña
        txtPassword.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txtPassword.setBackground(new Color(248, 250, 252));
        txtPassword.setForeground(new Color(15, 23, 42));
        txtPassword.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(203, 213, 225), 1),
                BorderFactory.createEmptyBorder(5, 10, 5, 10) // Padding interno
        ));
        txtPassword.setBounds(50, 200, 310, 38);
        pnlLogin.add(txtPassword);

        // btnIniciarSesion: Botón principal
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnIniciarSesion.setBackground(new Color(37, 99, 235)); // Azul profesional
        btnIniciarSesion.setForeground(Color.WHITE);
        btnIniciarSesion.setFocusPainted(false);
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnIniciarSesion.setBounds(50, 260, 310, 42);
        pnlLogin.add(btnIniciarSesion);

        // lblMensaje: Mensajes de error, aviso o "¿Problemas para entrar?"
        lblMensaje.setText("¿Problemas para entrar?");
        lblMensaje.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblMensaje.setForeground(new Color(100, 116, 139));
        lblMensaje.setHorizontalAlignment(SwingConstants.CENTER);
        lblMensaje.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblMensaje.setBounds(50, 320, 310, 25);
        pnlLogin.add(lblMensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
