/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas.menus;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import modelos.Usuario;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;
import vistas.FrmAdministrador.FrmCuentas;
import vistas.FrmMenuPrincipal;
import vistas.FrmLogin;
import vistas.FrmAdministrador.FrmUsuarios;

/**
 *
 * @author Nehemias Valencia
 */
public class FrmMenuAdmin extends javax.swing.JPanel {

    private Usuario usuario;
    private FrmMenuPrincipal menuPrincipal;

    /**
     * Creates new form FrmMenus
     */
    public FrmMenuAdmin(Usuario usuario, FrmMenuPrincipal menuPrincipal) {

        this.usuario = usuario;
        this.menuPrincipal = menuPrincipal;
        initComponents();
        initializeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        lblBienvenida = new javax.swing.JLabel();
        btnCuentas = new javax.swing.JButton();
        btnAsientos = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnOperaciones = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnPeríodosContables = new javax.swing.JButton();
        btnImpuestos = new javax.swing.JButton();
        brnHistorial = new javax.swing.JButton();
        btnEmpresa = new javax.swing.JButton();

        lblTitulo.setText("Sistema Contable");

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);

        lblBienvenida.setText("Bienvenido, Administrador");

        btnCuentas.setText("Catalago de cuentas");
        btnCuentas.addActionListener(this::btnCuentasActionPerformed);

        btnAsientos.setText("Libro diario");

        btnProductos.setText("Productos");
        btnProductos.addActionListener(this::btnProductosActionPerformed);

        btnReportes.setText("Reportes");

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        btnOperaciones.setText("Operaciones");

        btnConfiguracion.setText("Configuracion");

        btnDashboard.setText("Dashboard");

        btnPeríodosContables.setText("Períodos contables");

        btnImpuestos.setText("Impuestos");
        btnImpuestos.addActionListener(this::btnImpuestosActionPerformed);

        brnHistorial.setText("Historial");

        btnEmpresa.setText("Empresa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblBienvenida))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnProductos)
                                    .addGap(55, 55, 55))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnUsuarios)
                                        .addComponent(btnCuentas)
                                        .addComponent(btnAsientos)
                                        .addComponent(btnOperaciones))))
                            .addComponent(btnDashboard)
                            .addComponent(btnPeríodosContables)
                            .addComponent(btnImpuestos)
                            .addComponent(btnReportes)
                            .addComponent(brnHistorial)
                            .addComponent(btnConfiguracion)
                            .addComponent(btnCerrarSesion)
                            .addComponent(btnEmpresa))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard)
                .addGap(4, 4, 4)
                .addComponent(btnPeríodosContables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCuentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOperaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImpuestos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brnHistorial)
                .addGap(9, 9, 9)
                .addComponent(btnEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfiguracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        FrmUsuarios frmUsuarios
                = new FrmUsuarios(usuario, menuPrincipal);

        menuPrincipal.mostrarVentana(frmUsuarios);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);

        menuPrincipal.dispose();

    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnImpuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImpuestosActionPerformed

    private void btnCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasActionPerformed
        FrmCuentas frmCuentas
                = new FrmCuentas(usuario, menuPrincipal);

        menuPrincipal.mostrarVentana(frmCuentas);
    }//GEN-LAST:event_btnCuentasActionPerformed

    public void initializeComponents() {
        // 1. Fondo general neutro y limpio
        this.setBackground(new Color(248, 250, 252)); // Slate 50

        // 2. Encabezados con jerarquía visual moderna
        if (lblTitulo != null) {
            lblTitulo.setText("SISTEMA CONTABLE");
            lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 20));
            lblTitulo.setForeground(new Color(15, 23, 42)); // Slate 900
        }

        if (lblBienvenida != null) {
            lblBienvenida.setText("Bienvenido, Administrador");
            lblBienvenida.setFont(new Font("Segoe UI", Font.PLAIN, 13));
            lblBienvenida.setForeground(new Color(100, 116, 139)); // Slate 500
        }

        // 3. Paleta de colores moderna (Indigo SaaS Style)
        Font fontBotones = new Font("Segoe UI", Font.BOLD, 13);

        Color colorFondoNormal = new Color(79, 70, 229);   // Indigo 600
        Color colorFondoHover = new Color(99, 102, 241);  // Indigo 500
        Color colorFondoPress = new Color(67, 56, 202);   // Indigo 700
        Color colorTextoBoton = new Color(255, 255, 255); // Blanco puro

        // Botones del menú
        JButton[] botonesMenu = {
            btnDashboard,
            btnUsuarios,
            btnCuentas,
            btnAsientos,
            btnOperaciones,
            btnProductos,
            btnReportes,
            btnConfiguracion,
            btnEmpresa,
            btnImpuestos,
            btnPeríodosContables,
            brnHistorial
        };

        // Aplicar estilos a cada botón del menú
        for (JButton btn : botonesMenu) {
            if (btn != null) {
                estilarBotonRedondeado(btn, fontBotones, colorFondoNormal, colorFondoHover, colorFondoPress, colorTextoBoton);
            }
        }

        // 4. Estilo diferenciado para "Cerrar Sesión" (Estilo Rose / Crimson Moderno)
        if (btnCerrarSesion != null) {
            Color colorRojoNormal = new Color(225, 29, 72); // Rose 600
            Color colorRojoHover = new Color(244, 63, 94);  // Rose 500
            Color colorRojoPress = new Color(190, 18, 60);  // Rose 700

            estilarBotonRedondeado(btnCerrarSesion, fontBotones, colorRojoNormal, colorRojoHover, colorRojoPress, Color.WHITE);
        }

        // Refrescar la interfaz gráfica
        this.revalidate();
        this.repaint();
    }

    /**
     * Clase para crear botones con bordes suavemente redondeados y renderizado
     * suavizado.
     */
    private class BotonRedondeado extends JButton {

        private Color backgroundColor;
        private int radio = 14; // Radio de bordes más suave (14px)

        public BotonRedondeado(String text) {
            super(text);
            setContentAreaFilled(false);
            setFocusPainted(false);
            setBorderPainted(false);
            setOpaque(false);
        }

        public void setCustomBackground(Color bg) {
            this.backgroundColor = bg;
            repaint();
        }

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g.create();

            // Habilitar Antialiasing para bordes suaves
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            // Pintar el fondo redondeado
            g2.setColor(backgroundColor != null ? backgroundColor : getBackground());
            g2.fill(new RoundRectangle2D.Float(0, 0, getWidth(), getHeight(), radio, radio));

            g2.dispose();
            super.paintComponent(g);
        }
    }

    /**
     * Método auxiliar para aplicar el estilo visual limpio y moderno a los
     * botones.
     */
    private void estilarBotonRedondeado(JButton btn, Font fuente, Color bgNormal, Color bgHover, Color bgPress, Color fgColor) {
        btn.setFont(fuente);
        btn.setBackground(bgNormal);
        btn.setForeground(fgColor);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setOpaque(false);
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Alineación a la izquierda
        btn.setHorizontalAlignment(SwingConstants.LEFT);

        // Tamaño uniforme (Ancho: 220px, Alto: 42px)
        Dimension tamanoUniforme = new Dimension(220, 42);
        btn.setPreferredSize(tamanoUniforme);
        btn.setMinimumSize(tamanoUniforme);
        btn.setMaximumSize(tamanoUniforme);

        // Margen interno (padding): 0 arriba/abajo, 20px izquierda/derecha
        btn.setBorder(new EmptyBorder(0, 20, 0, 20));

        if (btn instanceof BotonRedondeado) {
            ((BotonRedondeado) btn).setCustomBackground(bgNormal);
        }

        // Limpiar listeners antiguos antes de agregar uno nuevo para evitar acumulaciones
        for (var listener : btn.getMouseListeners()) {
            if (listener.getClass().getName().contains("EstiloHoverListener")) {
                btn.removeMouseListener(listener);
            }
        }

        // Listener para Hover y Press
        btn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent evt) {
                actualizarColor(bgHover);
            }

            @Override
            public void mouseExited(MouseEvent evt) {
                actualizarColor(bgNormal);
            }

            @Override
            public void mousePressed(MouseEvent evt) {
                actualizarColor(bgPress);
            }

            @Override
            public void mouseReleased(MouseEvent evt) {
                if (btn.getBounds().contains(evt.getPoint())) {
                    actualizarColor(bgHover);
                } else {
                    actualizarColor(bgNormal);
                }
            }

            private void actualizarColor(Color color) {
                if (btn instanceof BotonRedondeado) {
                    ((BotonRedondeado) btn).setCustomBackground(color);
                } else {
                    btn.setBackground(color);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnHistorial;
    private javax.swing.JButton btnAsientos;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnCuentas;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnEmpresa;
    private javax.swing.JButton btnImpuestos;
    private javax.swing.JButton btnOperaciones;
    private javax.swing.JButton btnPeríodosContables;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
